config/routes.rb
Rails.application.routes.draw do
  # get 'pages/home'
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :share_videos, path: 'share',  only: [:create] do
    collection do
      get :new
    end
  end

  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/share_video.rb
class ShareVideo < ApplicationRecord
  include ApplicationHelper

  validates :url, presence: true
  validate :validate_for_youtube_url

  belongs_to :user

  scope :recent, -> {order(created_at: :desc)}

  def youtube_id
    get_youtube_id(url)
  end

  def validate_for_youtube_url
    return if url.blank?

    regexp = /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})?$/
    return if url =~ regexp
    message = 'is invalid'
    errors.add(:url, message)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :share_videos

  protected

  # From Devise module Validatable
  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @shared_videos = ShareVideo.all.recent
  end
end

app/controllers/share_videos_controller.rb
class ShareVideosController < ApplicationController
  before_action :authenticate_user!

  def new
    @video = ShareVideo.new
  end

  def create
    @video = ShareVideo.new(user: current_user, url: params['share_video']['url'])
    if @video.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/users/custom_failure.rb
class CustomFailure < Devise::FailureApp
  def redirect_url
    root_path
  end

  def respond
    if http_auth?
      http_auth
    else
      redirect
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    user_username = params[:user][:username]

    user = User.find_by_username user_username

    if user.present?
      super
    else
      create_user
    end
  end

  def create_user
    build_resource(sign_up_params)

    resource.save
    if resource.persisted?
      set_flash_message! :notice, :signed_up
      sign_up(resource_name, resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
      redirect_to root_path(resource)
    end
  end

  def sign_up_params
    params.require(:user).permit(:username, :password)
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_youtube_id(url)
    return '' if url.nil?
    id = ''
    url = url.gsub(/(>|<)/i, '').split(/(vi\/|v=|\/v\/|youtu\.be\/|\/embed\/)/)
    if !url[2].nil?
      id = url[2].split(/[^0-9a-z_\-]/i)
      id = id[0]
    else
      id = url
    end
    id
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "pages/pages_partial/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="main" class="wrapper">
  <div class="movies">
      <% @shared_videos.each do |video| %>
        <div class="card">
          <div class="movie-iframe">
          <iframe width="350" height="200"
            src="https://www.youtube.com/embed/<%=video.youtube_id%>">
          </iframe>
          </div>
          <div class="movie-content">
            <h2 class="title">Movie Title</h2>
            <h5 class="share-by">Share by: <%= video.user.username %></h5>
            <div class="like-bok">
              <span class="mgr10">89 <i class="bg-icon like-icon"></i></span>
              <span>89 <i class="bg-icon dislike-icon"></i></span>
            </div>
            <div>Description: </div>
            <p class="desc">It only takes a sentence to change your life. The best writers and thinkers are able to sum up a big thought or concept in just a few simple words. Delight in the following quotes that can get you up ...</p>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/pages/pages_partial/_header.html.erb
<header>
  <div class="header wrapper flex-center">
    <div class="header-logo">
      <a class="flex-center" href="/">
        <div class="home-logo-svg">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="460.298px" height="460.297px" viewBox="0 0 460.298 460.297" style="enable-background:new 0 0 460.298 460.297;" xml:space="preserve">
            <g>
              <g>
                <path d="M230.149,120.939L65.986,256.274c0,0.191-0.048,0.472-0.144,0.855c-0.094,0.38-0.144,0.656-0.144,0.852v137.041    c0,4.948,1.809,9.236,5.426,12.847c3.616,3.613,7.898,5.431,12.847,5.431h109.63V303.664h73.097v109.64h109.629    c4.948,0,9.236-1.814,12.847-5.435c3.617-3.607,5.432-7.898,5.432-12.847V257.981c0-0.76-0.104-1.334-0.288-1.707L230.149,120.939    z"/>
                <path d="M457.122,225.438L394.6,173.476V56.989c0-2.663-0.856-4.853-2.574-6.567c-1.704-1.712-3.894-2.568-6.563-2.568h-54.816    c-2.666,0-4.855,0.856-6.57,2.568c-1.711,1.714-2.566,3.905-2.566,6.567v55.673l-69.662-58.245    c-6.084-4.949-13.318-7.423-21.694-7.423c-8.375,0-15.608,2.474-21.698,7.423L3.172,225.438c-1.903,1.52-2.946,3.566-3.14,6.136    c-0.193,2.568,0.472,4.811,1.997,6.713l17.701,21.128c1.525,1.712,3.521,2.759,5.996,3.142c2.285,0.192,4.57-0.476,6.855-1.998    L230.149,95.817l197.57,164.741c1.526,1.328,3.521,1.991,5.996,1.991h0.858c2.471-0.376,4.463-1.43,5.996-3.138l17.703-21.125    c1.522-1.906,2.189-4.145,1.991-6.716C460.068,229.007,459.021,226.961,457.122,225.438z"/>
              </g>
            </g>
          </svg>
        </div>
        <div class="logo-text">Funny Movies</div>
      </a>
    </div>
    <div class="main-nav">
      <nav>
        <% if current_user.present? %>
          <ul class="menu">
              <li class="item">
                Welcome <%= current_user.username %>
              </li>
              <li class="item">
                <%= link_to 'Share a movie', share_videos_path, class: 'btn mgl10' %>
              </li>
              <li class="item">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn mgl10' %>
              </li>
            </ul>
        <% else %>
          <%= form_for(:user, url: session_path(:user)) do |f| %>
            <ul class="menu">
              <li class="item">
                <%= f.text_field :username, class: 'input-form'  %>
              </li>
              <li class="item">
                <%= f.password_field :password, class: 'input-form' %>
              </li>
              <li class="item">
                <%= f.submit 'Login / Register', class: 'btn' %>
              </li>
            </ul>
          <% end %>
        <% end %>
        <div class="failed-message">
          <% flash.each do |name, msg| %>
            <% if msg.class == Array %>
              <% msg.each do |message| %>
                <%= content_tag :div, message, class: "msg comma" %>
              <% end %>
            <% else %>
            <%= content_tag :div, msg, class: "flash hide-me" %>
            <% end %>
          <% end %>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/share_videos/new.html.erb
<div id="main" class="wrapper">
  <div class='video-box'>
    <span class='innertext'>Share a Youtube movie</span>
    <div class='share-video'>
      <%= form_for @video, url: share_videos_path, method: :post do |f| %>
        <div class="flex-center">
          <%= f.label :url, "Youtube URL:", class:'text-sm' %>
          <%= f.text_field :url, class: "input-form w200 mgl10" %>
        </div>
        <% @video.errors.full_messages_for(:url).each do |message| %>
          <div class="failed-ms"><%= message %></div>
        <% end %>
        <div class="text-right">
          <%= f.submit 'Share', class: 'btn w200 mgl10' %>
        </div>
      <% end %>
    </div>
  </div>
</div>